version: '3'
services:
  syqpass-db:
    image: mongo:6
    container_name: syqpass-db
    restart: unless-stopped
    hostname: syqpass-db
    volumes:
      - /opt/syqpass/data:/data/db
    ports:
      - "6000:27017"
    networks:
      - syqpass_net
    healthcheck:
      test: ["CMD", "mongo", "--eval", "printjson(db.adminCommand('ping'))"]
      interval: 30s
      timeout: 10s
      retries: 3

  syqpass-web:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: syqpass-web
    hostname: syqpass-web
    volumes:
      - /opt/syqpass/web:/app/dist
      - /opt/syqpass/
    networks:
      - syqpass_net
    depends_on:
      - api

  syqpass-api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: syqpass-api
    restart: unless-stopped
    hostname: syqpass-api
    volumes:
      - /opt/syqpass/config/api:/app/config
      - /opt/syqpass/log:/var/log/syqpass
    ports:
      - "4000:4000"
    networks:
      - syqpass_net
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://syqpass-api:4000/"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  syqpass_net:
    driver: bridge
